// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { maybeFilter } from 'test_wiz-mcp/filtering';
import { Metadata, asTextContentResult } from 'test_wiz-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import TestWiz from 'test_wiz';

export const metadata: Metadata = {
  resource: 'customers',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/v1/customers',
};

export const tool: Tool = {
  name: 'create_customers',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\nCreate Customer\n\n# Response Schema\n```json\n{\n  $ref: '#/$defs/customer_create_response',\n  $defs: {\n    customer_create_response: {\n      allOf: [        {\n          $ref: '#/$defs/success'\n        }\n      ]\n    },\n    success: {\n      type: 'object',\n      properties: {\n        data: {\n          type: 'object',\n          additionalProperties: true\n        }\n      }\n    }\n  }\n}\n```",
  inputSchema: {
    type: 'object',
    properties: {
      assigned_price_list_id: {
        type: 'string',
        description: 'Price list id is a uuid can be queried from price list api',
      },
      assigned_sales_rep_ids: {
        type: 'array',
        description: 'List of sales rep ids, sales rep id is a uuid can be queried from sales rep api',
        items: {
          type: 'string',
        },
      },
      reference_id: {
        type: 'string',
      },
      addresses: {
        type: 'array',
        items: {
          $ref: '#/$defs/address_create',
        },
      },
      attributes: {
        type: 'array',
        items: {
          $ref: '#/$defs/attribute_request',
        },
      },
      company_name: {
        type: 'string',
      },
      contacts: {
        type: 'array',
        items: {
          $ref: '#/$defs/contact_create',
        },
      },
      display_id: {
        type: 'string',
        description: 'This is the display ID of the customer, it is generated by the system if not provided.',
      },
      display_name: {
        type: 'string',
      },
      email: {
        type: 'string',
      },
      first_name: {
        type: 'string',
      },
      freight_term: {
        type: 'string',
      },
      last_name: {
        type: 'string',
      },
      payment_mode: {
        type: 'string',
      },
      payment_term: {
        type: 'string',
      },
      phone: {
        type: 'string',
        description: 'Phone number in E.164 format',
      },
      shipping_method: {
        type: 'string',
      },
      jq_filter: {
        type: 'string',
        title: 'jq Filter',
        description:
          'A jq filter to apply to the response to include certain fields. Consult the output schema in the tool description to see the fields that are available.\n\nFor example: to include only the `name` field in every object of a results array, you can provide ".results[].name".\n\nFor more information, see the [jq documentation](https://jqlang.org/manual/).',
      },
    },
    required: ['assigned_price_list_id', 'assigned_sales_rep_ids', 'reference_id'],
    $defs: {
      address_create: {
        type: 'object',
        properties: {
          address_line_1: {
            type: 'string',
          },
          city: {
            type: 'string',
          },
          reference_id: {
            type: 'string',
          },
          type: {
            type: 'string',
            enum: ['billing', 'shipping'],
          },
          address_line_2: {
            type: 'string',
          },
          attributes: {
            type: 'array',
            items: {
              $ref: '#/$defs/attribute_request',
            },
          },
          country: {
            type: 'string',
            description: 'Country code in ISO 3166-1 alpha-2 format, e.g. US, IN, etc.',
          },
          email: {
            type: 'string',
          },
          first_name: {
            type: 'string',
          },
          is_default: {
            type: 'boolean',
            description: 'Default address for the customer',
          },
          last_name: {
            type: 'string',
          },
          phone: {
            type: 'string',
            description: 'Phone number in E.164 format',
          },
          state: {
            type: 'string',
          },
          zip_code: {
            type: 'string',
          },
        },
        required: ['address_line_1', 'city', 'reference_id', 'type'],
      },
      attribute_request: {
        type: 'object',
        properties: {
          name: {
            type: 'string',
          },
          value: {
            type: 'string',
          },
        },
        required: ['name', 'value'],
      },
      contact_create: {
        type: 'object',
        properties: {
          email: {
            type: 'string',
          },
          first_name: {
            type: 'string',
          },
          reference_id: {
            type: 'string',
          },
          attributes: {
            type: 'array',
            items: {
              $ref: '#/$defs/attribute_request',
            },
          },
          designation: {
            type: 'string',
          },
          is_default: {
            type: 'boolean',
            description: 'Default contact for the customer',
          },
          last_name: {
            type: 'string',
          },
          phone: {
            type: 'string',
            description: 'Phone number in E.164 format',
          },
        },
        required: ['email', 'first_name', 'reference_id'],
      },
    },
  },
  annotations: {},
};

export const handler = async (client: TestWiz, args: Record<string, unknown> | undefined) => {
  const { jq_filter, ...body } = args as any;
  return asTextContentResult(await maybeFilter(jq_filter, await client.customers.create(body)));
};

export default { metadata, tool, handler };
