// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { maybeFilter } from 'test_wiz-mcp/filtering';
import { Metadata, asTextContentResult } from 'test_wiz-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import TestWiz from 'test_wiz';

export const metadata: Metadata = {
  resource: 'customers',
  operation: 'write',
  tags: [],
  httpMethod: 'patch',
  httpPath: '/v1/customers/{id}',
};

export const tool: Tool = {
  name: 'update_customers',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\nUpdate Customer\n\n# Response Schema\n```json\n{\n  allOf: [    {\n      $ref: '#/$defs/success'\n    }\n  ],\n  $defs: {\n    success: {\n      type: 'object',\n      properties: {\n        data: {\n          type: 'object',\n          additionalProperties: true\n        }\n      }\n    }\n  }\n}\n```",
  inputSchema: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
      },
      addresses: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: {
              type: 'string',
            },
            address_line_1: {
              type: 'string',
            },
            address_line_2: {
              type: 'string',
            },
            attributes: {
              type: 'array',
              items: {
                $ref: '#/$defs/attribute_request',
              },
            },
            city: {
              type: 'string',
            },
            country: {
              type: 'string',
              description: 'Country code in ISO 3166-1 alpha-2 format, e.g. US, IN, etc.',
            },
            email: {
              type: 'string',
            },
            first_name: {
              type: 'string',
            },
            is_default: {
              type: 'boolean',
              description: 'Default address for the customer',
            },
            last_name: {
              type: 'string',
            },
            phone: {
              type: 'string',
              description: 'Phone number in E.164 format',
            },
            reference_id: {
              type: 'string',
            },
            state: {
              type: 'string',
            },
            type: {
              type: 'string',
              enum: ['billing', 'shipping'],
            },
            zip_code: {
              type: 'string',
            },
          },
          required: ['id'],
        },
      },
      assigned_price_list_id: {
        type: 'string',
        description: 'Price list id is a uuid can be queried from price list api',
      },
      assigned_sales_rep_ids: {
        type: 'array',
        description: 'List of sales rep ids, sales rep id is a uuid can be queried from sales rep api',
        items: {
          type: 'string',
        },
      },
      attributes: {
        type: 'array',
        items: {
          $ref: '#/$defs/attribute_request',
        },
      },
      company_name: {
        type: 'string',
      },
      contacts: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: {
              type: 'string',
            },
            attributes: {
              type: 'array',
              items: {
                $ref: '#/$defs/attribute_request',
              },
            },
            designation: {
              type: 'string',
            },
            email: {
              type: 'string',
            },
            first_name: {
              type: 'string',
            },
            is_default: {
              type: 'boolean',
              description: 'Default contact for the customer',
            },
            last_name: {
              type: 'string',
            },
            phone: {
              type: 'string',
              description: 'Phone number in E.164 format',
            },
            reference_id: {
              type: 'string',
            },
          },
          required: ['id'],
        },
      },
      default_billing_address_id: {
        type: 'string',
      },
      default_shipping_address_id: {
        type: 'string',
      },
      display_id: {
        type: 'string',
        description: 'This is the display ID of the customer, it is generated by the system if not provided.',
      },
      display_name: {
        type: 'string',
      },
      email: {
        type: 'string',
      },
      first_name: {
        type: 'string',
      },
      freight_term: {
        type: 'string',
      },
      last_name: {
        type: 'string',
      },
      payment_mode: {
        type: 'string',
      },
      payment_term: {
        type: 'string',
      },
      phone: {
        type: 'string',
        description: 'Phone number in E.164 format',
      },
      primary_contact_id: {
        type: 'string',
      },
      reference_id: {
        type: 'string',
      },
      shipping_method: {
        type: 'string',
      },
      jq_filter: {
        type: 'string',
        title: 'jq Filter',
        description:
          'A jq filter to apply to the response to include certain fields. Consult the output schema in the tool description to see the fields that are available.\n\nFor example: to include only the `name` field in every object of a results array, you can provide ".results[].name".\n\nFor more information, see the [jq documentation](https://jqlang.org/manual/).',
      },
    },
    required: ['id'],
    $defs: {
      attribute_request: {
        type: 'object',
        properties: {
          name: {
            type: 'string',
          },
          value: {
            type: 'string',
          },
        },
        required: ['name', 'value'],
      },
    },
  },
  annotations: {},
};

export const handler = async (client: TestWiz, args: Record<string, unknown> | undefined) => {
  const { id, jq_filter, ...body } = args as any;
  return asTextContentResult(await maybeFilter(jq_filter, await client.customers.update(id, body)));
};

export default { metadata, tool, handler };
