// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { maybeFilter } from 'test_wiz-mcp/filtering';
import { Metadata, asTextContentResult } from 'test_wiz-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import TestWiz from 'test_wiz';

export const metadata: Metadata = {
  resource: 'orders',
  operation: 'write',
  tags: [],
  httpMethod: 'put',
  httpPath: '/v2/orders/{id}',
};

export const tool: Tool = {
  name: 'update_orders',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\nUpdate order\n\n# Response Schema\n```json\n{\n  allOf: [    {\n      $ref: '#/$defs/success'\n    }\n  ],\n  $defs: {\n    success: {\n      type: 'object',\n      properties: {\n        data: {\n          type: 'object',\n          additionalProperties: true\n        }\n      }\n    }\n  }\n}\n```",
  inputSchema: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
      },
      created_at: {
        type: 'string',
      },
      customer_id: {
        type: 'string',
      },
      fulfillment_status: {
        type: 'string',
        enum: [
          'PARTIALLY_DELIVERED',
          'UNFULFILLED',
          'PARTIALLY_FULFILLED',
          'FULFILLED',
          'IN_PROGRESS',
          'DELIVERED',
        ],
      },
      line_items: {
        type: 'array',
        items: {
          $ref: '#/$defs/order_line_item_request_v2',
        },
      },
      payment_status: {
        type: 'string',
        enum: ['PAID', 'PENDING', 'PARTIALLY_PAID', 'REFUNDED', 'OVERPAID', 'VOIDED'],
      },
      reference_id: {
        type: 'string',
      },
      updated_at: {
        type: 'string',
        description: 'Updated at must be later than the order creation date',
      },
      additional_charges: {
        type: 'array',
        description:
          'These are additional charges on the order apart from shipping, tax, discount, etc. It will be add-on to the total amount of the order.',
        items: {
          $ref: '#/$defs/order_charges_request_v2',
        },
      },
      amount: {
        type: 'number',
        description:
          'This is total amount of the order before all discounts, taxes, shipping charges, etc. are applied.',
      },
      amount_paid: {
        type: 'number',
      },
      attributes: {
        type: 'array',
        items: {
          $ref: '#/$defs/attribute_request',
        },
      },
      billing_address: {
        $ref: '#/$defs/order_address_request_v2',
      },
      container_info: {
        $ref: '#/$defs/container_info_request_v2',
      },
      customer_consent: {
        $ref: '#/$defs/customer_consent_request_v2',
      },
      customer_note: {
        type: 'string',
      },
      discount_value: {
        type: 'number',
        description:
          'Discount offered on the order, always amount of actual discount offered. e.g. if discount is 10% off, then discount value is 10.00 for 100.00 amount',
      },
      display_id: {
        type: 'string',
        description: 'This is the display ID of the order, it is generated by the system if not provided.',
      },
      due_date: {
        type: 'string',
        description:
          'Due date must be later than the order creation date, send null if due date is not applicable',
      },
      freight_term: {
        type: 'string',
      },
      internal_note: {
        type: 'string',
      },
      payment_method_id: {
        type: 'string',
      },
      payment_term: {
        type: 'string',
      },
      po_number: {
        type: 'string',
      },
      primary_contact: {
        $ref: '#/$defs/order_contact_request_v2',
      },
      shipment_date: {
        type: 'string',
        description: 'Shipment date must be later than the order creation date',
      },
      shipping_address: {
        $ref: '#/$defs/order_address_request_v2',
      },
      shipping_charge: {
        type: 'number',
        description:
          'Shipping charge on the order, always amount of actual shipping charge offered. e.g. if shipping charge is $10.00, then shipping charge is $10.00',
      },
      shipping_method: {
        type: 'string',
      },
      source: {
        type: 'string',
        description: 'Source of the order, if not provided then it will be openapi',
      },
      tax_value: {
        type: 'number',
        description:
          'Tax value on the order, always amount of actual tax offered. e.g. if tax is 10% of amount, then tax value is 10.00 for 100.00 amount',
      },
      jq_filter: {
        type: 'string',
        title: 'jq Filter',
        description:
          'A jq filter to apply to the response to include certain fields. Consult the output schema in the tool description to see the fields that are available.\n\nFor example: to include only the `name` field in every object of a results array, you can provide ".results[].name".\n\nFor more information, see the [jq documentation](https://jqlang.org/manual/).',
      },
    },
    required: [
      'id',
      'created_at',
      'customer_id',
      'fulfillment_status',
      'line_items',
      'payment_status',
      'reference_id',
      'updated_at',
    ],
    $defs: {
      order_line_item_request_v2: {
        type: 'object',
        properties: {
          sku: {
            type: 'string',
          },
          cancelled_quantity: {
            type: 'integer',
          },
          discount: {
            type: 'number',
            description:
              'Discount on the product, this is the discount amount that is applied to the product at unit price level.',
          },
          discount_type: {
            type: 'string',
            description: 'Discount type can be percentage or value.',
            enum: ['percentage', 'value'],
          },
          invoiced_quantity: {
            type: 'integer',
          },
          is_adhoc: {
            type: 'boolean',
          },
          note: {
            type: 'string',
          },
          picked_quantity: {
            type: 'integer',
          },
          quantity: {
            type: 'integer',
          },
          shipped_quantity: {
            type: 'integer',
          },
          unit_price: {
            type: 'number',
            description:
              'Unit price of the product, this is the price of the product before any discounts are applied.',
          },
        },
        required: ['sku'],
      },
      order_charges_request_v2: {
        type: 'object',
        properties: {
          name: {
            type: 'string',
          },
          type: {
            type: 'string',
            description:
              'If charge is tax then charge amount will be added to the amount. If charge is discount then it will be subtracted from the amount.',
            enum: ['tax', 'discount'],
          },
          amount: {
            type: 'number',
          },
        },
        required: ['name', 'type'],
      },
      attribute_request: {
        type: 'object',
        properties: {
          name: {
            type: 'string',
          },
          value: {
            type: 'string',
          },
        },
        required: ['name', 'value'],
      },
      order_address_request_v2: {
        type: 'object',
        properties: {
          id: {
            type: 'string',
          },
          address_line_1: {
            type: 'string',
          },
          address_line_2: {
            type: 'string',
          },
          attributes: {
            type: 'array',
            items: {
              $ref: '#/$defs/attribute_request',
            },
          },
          city: {
            type: 'string',
          },
          country: {
            type: 'string',
            description: 'Country code in ISO 3166-1 alpha-2 format, e.g. US, IN, etc.',
          },
          email: {
            type: 'string',
          },
          first_name: {
            type: 'string',
          },
          last_name: {
            type: 'string',
          },
          phone: {
            type: 'string',
            description: 'Phone number in E.164 format',
          },
          reference_id: {
            type: 'string',
          },
          state: {
            type: 'string',
          },
          zip_code: {
            type: 'string',
          },
        },
      },
      container_info_request_v2: {
        type: 'object',
        properties: {
          key: {
            type: 'string',
          },
          unit: {
            type: 'string',
            enum: ['CFT', 'CBM'],
          },
          volume: {
            type: 'number',
          },
          name: {
            type: 'string',
          },
        },
        required: ['key', 'unit', 'volume'],
      },
      customer_consent_request_v2: {
        type: 'object',
        properties: {
          consent_file_id: {
            type: 'string',
          },
          has_consent: {
            type: 'boolean',
          },
        },
        required: ['consent_file_id', 'has_consent'],
      },
      order_contact_request_v2: {
        type: 'object',
        properties: {
          id: {
            type: 'string',
          },
          attributes: {
            type: 'array',
            items: {
              $ref: '#/$defs/attribute_request',
            },
          },
          designation: {
            type: 'string',
          },
          email: {
            type: 'string',
          },
          first_name: {
            type: 'string',
          },
          last_name: {
            type: 'string',
          },
          phone: {
            type: 'string',
            description: 'Phone number in E.164 format',
          },
        },
      },
    },
  },
  annotations: {
    idempotentHint: true,
  },
};

export const handler = async (client: TestWiz, args: Record<string, unknown> | undefined) => {
  const { id, jq_filter, ...body } = args as any;
  return asTextContentResult(await maybeFilter(jq_filter, await client.orders.update(id, body)));
};

export default { metadata, tool, handler };
